
project_id = "jbcurgdwbvjsgbftjejg"

[functions.connect-wordpress]
verify_jwt = true

[functions.connect-wordpress-self-hosted]
verify_jwt = true

[functions.oauth-facebook]
verify_jwt = true

[functions.oauth-instagram]
verify_jwt = true

[functions.oauth-wordpress]
verify_jwt = true

[functions.publish-facebook]
verify_jwt = true

[functions.publish-instagram]
verify_jwt = true

[functions.publish-wordpress]
verify_jwt = true

[functions.revoke-facebook]
verify_jwt = true

[functions.revoke-instagram]
verify_jwt = true

[functions.revoke-wordpress]
verify_jwt = true
