// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbcurgdwbvjsgbftjejg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiY3VyZ2R3YnZqc2diZnRqZWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjczODMsImV4cCI6MjA2MTA0MzM4M30.wOf5E0_UQGmvAGEaUrPUg6oVZxnuZhRmrfVw_XIqgeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);